### ISSUE TITLE
Question about juvi (juniperus virginiana)

### ISSUE THREAD

**Issue by mcgregorian1** [SCBI-ForestGEO/SCBI-Plot-Book#12]
I noticed that we have one tagged species in our survey list that's not in our [official species list](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/species_lists/Tree%20ecology/SCBI_ForestGEO_sp_ecology.csv). We're not including it as a main sp in the book because our only record of it is from 2008 when it was dead.

However, during this past survey we sporadically found small juvi throughout a lot of the plot. In addition, BIEN shows the sp range as completely covering the entire East Coast.

Should we include its presence as a note somewhere, as we're not giving it a full page?
- I ask this because even though it seems inconsequential currently, this could be useful to know in the future that at one point we recorded the presence of juvi (2008) and additionally found recruits trying to gain footholds. In this sense, I'm thinking of it in the same vein as all the small fram and cade (chestnut) that we saw but also aren't tagged. 
- I believe having knowledge like this, even if only included as a note somewhere, would be good to record for possible future analyses given climate change and how the species composition of the plot is changing.

**Comment by teixeirak** [comment]
It wouldn't hurt to add pages, or just a section of text, mentioning these.

**Comment by mcgregorian1** [comment]
Ok. Alyssa and I were looking at other under-represented species and we noticed we have a few that have fewer than 5 individuals in the plot (e.g. eual, juci, juvi, pipu, quco, qufa, qumi, qumu, viac, vire). 

For these, would it make sense to have a couple of these per page, instead of potentially having some white space if we gave them each a full page? Ultimately, though, this will be dependent on how much we have to say for each one (e.g. for the life history).

**Comment by gonzalezeb** [comment]
There are some plots with examples like this...look around..we can make a decision later..
Viburnum spp can be lumped in same page..for example..

**Comment by teixeirak** [comment]
For the first release (online version), we do not need to worry about saving space. For now, let's have these species follow the template when the relevant information is available. As we build up the book, the more common/important species will have more info/ take more space than some of these species.

I'm closing this for now, as we won't be giving special treatment for certain species in this first version.
