### ISSUE TITLE
Improve scbi location map

### ISSUE THREAD

**Issue by gonzalezeb** [SCBI-ForestGEO/SCBI-Plot-Book#13]
I believe @mcgregorian1 can use his magic on this. The map in chapter 2 needs some improvement. 
-  include a world map or an American continent map showing Va location.
- change word grid to plot
- zoom in in the regional map so the scbi property in pink shows a little bit more
- numbers in topolines should run parallel to the lines
- the plot map also needs a legend to indicate creek and road.
- include deer fence

**Comment by mcgregorian1** [comment]
@gonzalezeb I've updated the map and it's [here](https://github.com/SCBI-ForestGEO/SCBI-Plot-Book/tree/master/docs) until the full book is rendered again. Let me know if you want anything else changed.

**Comment by alyssaterrell** [comment]
@gonzalezeb I believe that this post can be closed now.
