### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBI-Plot-Book#23]
Here is a running list of minor items to fix:
- [x] put species distribution maps on their own line 
- [x] in species descriptions, put new lines for Species code, Conservation status, stratum
- [x] format geographic coordinates (currently "38 degrees 53’36.6“N, 78 degrees 08’43.4”W")

**Comment by gonzalezeb** [comment]
@teixeirak 
what do you mean with point 1 on this issue?
"put species distribution maps on their own page"

**Comment by teixeirak** [comment]
Sorry, that's confusing. I meant to put them on a new line and let them take up the width of the page.
